Contact form
Srilearns/Portfolio-Website-Mobile-First pull request #4
Opened 2023-07-11 22:43 UTC by Srilearns

Added the contact form in the Mobile First Portfolio Website.
Added input fields name, email , text message fields and submit button.
Created styling for the form based on Figma template 1
Implemented button actions

2023-07-11 23:36 UTC, Munsa1 requested changes
Hi @Srilearns, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Collaboration On Project Achieved :heavy_check_mark: 
Nice UI Design :heavy_check_mark: 
Descriptive PR :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._
### Important 🔴 
Am leaving a comment here due to insufficient files changed

- [ ] Kindly edit your MIT license agreement to reflect your name and app type
![image](https://github.com/Srilearns/Portfolio-Website-Mobile-First/assets/81932478/80e2ac75-231c-4925-adc3-e3d777c7d77a)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-11 23:36 UTC, Munsa1 commented on index.html
> +        </section>
- [ ] Good job creating the contact form, using the correct tags for semantic purposes, and adding all the required validations. However, we have a few minor issues to achieve a great design.

- Kindly align the background image to match the given template

Your design
![image](https://github.com/Srilearns/Portfolio-Website-Mobile-First/assets/81932478/62b990eb-f539-4bc6-a9b1-94baac526656)

Given design
![image](https://github.com/Srilearns/Portfolio-Website-Mobile-First/assets/81932478/9d235511-d551-4053-bd7f-ac597c23c30b)


- [ ] Kindly align the text area to align with the input fields and the `Get In Touch` button so as to match the given design. Hint, you can apply Flexbox to it as you have done for the other elements

Your design
![image](https://github.com/Srilearns/Portfolio-Website-Mobile-First/assets/81932478/19a4a20d-d991-4fb4-b2b6-0aefaa4e7dc8)

Given design
![image](https://github.com/Srilearns/Portfolio-Website-Mobile-First/assets/81932478/b9e560fa-e514-45c6-b002-9d02acc98897)

- [ ] Also add the two background images to the bottom of your design so as to match the given template

Given template
![image](https://github.com/Srilearns/Portfolio-Website-Mobile-First/assets/81932478/5416de2e-d30b-41af-9fd1-446488ddd208)

Your design
![image](https://github.com/Srilearns/Portfolio-Website-Mobile-First/assets/81932478/27fca1e0-b87d-4b6a-afe5-3f8f3e8b7bf3)

2023-07-11 23:36 UTC, Munsa1 commented on styles.css
> +}
- [ ] Good job adding the hover, active and disabled effects. Kindly add the `pressed` effect as well to meet the requirements.
![image](https://github.com/Srilearns/Portfolio-Website-Mobile-First/assets/81932478/0572a23b-74ca-4eff-9e9a-b62769ee9789)

2023-07-12 11:40 UTC, Alusp approved these changes
Hi @Srilearns, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![congratulations](https://media.giphy.com/media/qx8pi39Lwm9Xm2audb/giphy.gif)

## Highlights

- [ ] Professional PR Summary :heavy_check_mark: 
- [ ] Good UI design :heavy_check_mark: 
- [ ] Sets HTML Validations correctly :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-13 01:12 UTC, merged